config/routes.rb
Rails.application.routes.draw do
  resources :socars

  resources :themes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/socar.rb
class Socar < ApplicationRecord
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/socars_controller.rb
class SocarsController < ApplicationController
  before_action :set_socar, only: [:show, :edit, :update, :destroy]
  def index
    @socars = Socar.all
  end

  def show
  end

  def new
  end
  
  def create
    @socar = Socar.new(socar_params)
    if @socar.save
      redirect_to "/socars/#{@socar.id}"
    else
      redirect_to :back
    end
  end

  def edit
  end
  
  def update
    if @socar.update(socar_params)
      redirect_to "/socars/#{@socar.id}"
    else 
      redirect_to :back
    end
  end
  
  def destroy
    @socar.destroy
    redirect_to "/socars"
  end
  
  private
  
  def set_socar
    @socar = Socar.find(params[:id])
  end
  
  def socar_params
    {title: params[:title], contents: params[:contents]}
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/socars_helper.rb
module SocarsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/socars/edit.html.erb
<%= form_tag("/socars/#{@socar.id}", method: 'patch') do %>
    <%= text_field_tag :title, @socar.title %>
    <%= text_area_tag :contents, @socar.contents %>
    <%= submit_tag 'update' %>
<% end %>

app/views/socars/index.html.erb
<h1>Socar Index</h1>
<table>
    <thead>
        <th>title</th>
        <th>contents</th>
        <th col="3"></th>
    </thead>
    <tbody>
        <% @socars.each do |socar| %>
        <tr>
            <td><%= socar.title %></td>
            <td><%= socar.contents %></td>
            <td><%= link_to 'show', "/socars/#{socar.id}" %></td>
            <td><%= link_to 'edit', "/socars/#{socar.id}/edit" %></td>
            <td><%= link_to 'destroy', "/socars/#{socar.id}", method: 'DELETE' %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= link_to 'new', '/socars/new' %>

app/views/socars/new.html.erb
<%= form_tag('/socars') do %>
    <%= text_field_tag :title %>
    <%= text_area_tag :contents %>
    <%= submit_tag 'create' %>
<% end %>

app/views/socars/show.html.erb
<h1>Socars show</h1>
<hr/>
<h1><%= @socar.title %></h1>
<hr/>
<p><%= @socar.contents %></p>
<%= link_to 'edit', "/socars/#{@socar.id}/edit" %>
<%= link_to 'destroy', "/socars/#{@socar.id}", method: 'DELETE' %>

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.title %></td>
        <td><%= theme.description %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @theme.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @theme.description %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>